// Builds the "Continue with Claude" prompt block that ends every HTML tool.
// Static HTML can score, branch, and organize. It can't write. This is the bridge.
(function () {
  // spec: { role, task, context: [{label, value}], sections: [{title, items:[string]}], asks: [string] }
  function buildPrompt(spec) {
    var out = [];

    if (spec.role) out.push(spec.role, '');
    if (spec.task) out.push(spec.task, '');

    if (spec.context && spec.context.length) {
      out.push('## My race');
      spec.context.forEach(function (c) {
        if (c.value) out.push('- ' + c.label + ': ' + c.value);
      });
      out.push('');
    }

    (spec.sections || []).forEach(function (s) {
      if (!s.items || !s.items.length) return;
      out.push('## ' + s.title);
      s.items.forEach(function (i) {
        out.push('- ' + i);
      });
      out.push('');
    });

    if (spec.asks && spec.asks.length) {
      out.push('## What I need from you');
      spec.asks.forEach(function (a, i) {
        out.push(i + 1 + '. ' + a);
      });
      out.push('');
    }

    out.push('---');
    out.push('Generated by a WINNXT campaign tool — winnxt.com');

    return out.join('\n');
  }

  window.WinnxtHandoff = { buildPrompt: buildPrompt };
})();
